

import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/Navbar";
import Footer from "./components/footer/Footer";
import Scroll from "./scroll";
const raleway = Raleway({
  variable: '--font-raleway',
  subsets: ["latin"],
  weight: ['100', '300', '400', '700', '900'],
  display: 'swap',
});


export const metadata: Metadata = {
  title: "EcoSphere",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pl">
      <body className={`${raleway.variable}`}>
        <Navbar />
        <Scroll/>
        {children}
        <Footer />
      </body>
    </html>
  );
}
